### PR TITLE
Add vit model training notebook

### PR DESCRIPTION
**Pull request by evawGraphcore**

### CODE REVIEW

**Comment by evawGraphcore** [comment]
The executable has been uploaded to a new dataset: poplar-executables-pytorch-3-1-1 and so the dataset has changed.

**Comment by evawGraphcore** [comment]
This will require the new dataset being made public

**Comment by anjleeg-gcai** [comment]
LGTM

**Comment by evawGraphcore** [comment]
`{
  "vit-model-training": [
    {
      "benchmark_name": "vit-model-training",
      "benchmark_path": "/notebooks/.gradient/notebook-tests.yaml",
      "command": "python3 -m examples_utils.benchmarks.notebook_utils walkthrough.ipynb . --timeout 10000",
      "compilation_end_time": "1180.389375",
      "end_time": "2023-03-06 16:45:00.764869",
      "exitcode": 0,
      "log_paths": {
        "err": "/storage/test-reports-2023-03-06-16_07_54/log_pytorch-IPU-POD16_2023-03-06-16_10_43/vit-model-training/stderr.log",
        "out": "/storage/test-reports-2023-03-06-16_07_54/log_pytorch-IPU-POD16_2023-03-06-16_10_43/vit-model-training/stdout.log"
      },
      "params": {},
      "results": {
        "cmd": {
          "cmd": "python3 -m examples_utils.benchmarks.notebook_utils walkthrough.ipynb . --timeout 10000"
        },
        "env": {
          "env": "POPLAR_LOG_LEVEL=INFO POPART_LOG_LEVEL=INFO TF_CPP_VMODULE=poplar_compiler=1 "
        },
        "git_commit_hash": {
          "git_commit_hash": "786c5dd36551f9cce7b99914a5943a2be65db6d0"
        },
        "result": {
          "result": "True"
        },
        "test_duration": {
          "test_duration": 2041.235439
        },
        "total_compiling_time": {
          "mean": 1180.389375
        }
      },
      "start_time": "2023-03-06 16:10:59.529430",
      "test_duration": "2041.235439",
      "variant_name": "vit-model-training"
    }
  ]
}`

**Pull request merged**
